#!/usr/bin/env bash
set -o errexit

DOMAIN=${1:-magento.test}
EDITION=${2}
VERSION=${3}

curl -s https://raw.githubusercontent.com/Chris-Weeks/docker-magento2/refs/heads/dependabot/github_actions/actions/checkout-5/lib/template | bash

# &&'s are used below otherwise onelinesetup script fails/errors after bin/download
# ${:+""} format only includes parameters if they were explicitly set
bin/download ${EDITION:+"$EDITION"} ${VERSION:+"$VERSION"} \
  && bin/setup "${DOMAIN}"
